Squashed grok commits
mdaconta/xlm-eco-api pull request #9
Opened 2024-11-22 11:16 UTC by cdaconta

Removed EmbeddingProvider from class

Removed EmbeddingProvider from class

Added to config Grok and created GrokProvider.java

Changed class name on GrokProvider and added Grok config details on config.properties.template

Added import to XlmEcosystemServiceImpl

Addeed GrokProvider to META-INF

Changed supportsEmbeddings to false

Adding config.properties.template back.

2024-11-22 11:19 UTC, cdaconta commented
I didn't mean to close it.  whoops

2024-11-22 20:59 UTC, mdaconta commented
Excellent! I will review...

2024-11-22 21:06 UTC, mdaconta commented
The file config.properties.template should not have been deleted.  Please return that file to the repo.

2024-11-22 21:07 UTC, mdaconta requested changes
A few minor issues with this.  Please correct these and resubmit the PR.

2024-11-22 21:07 UTC, mdaconta commented on src/main/java/us/daconta/xlmeco/GrpcXlmServer.java
> +        Properties properties = loadProperties("config.properties.template");
You don't load the template.  Need to change this back to config.properties.  The template is only used to copy it to the config.properties file and add your API keys.  I actually have my "real" file stored away in another directory and I just copy it in when I want to test.

2024-11-22 21:07 UTC, mdaconta commented on src/main/java/us/daconta/xlmeco/provider/impl/GrokProvider.java
> +public class GrokProvider extends AbstractGenerativeProvider implements ChatProvider, EmbeddingProvider {
Why does it implement EmbeddingProvider if it cannot provide embeddings?  Recommend removing that and setting the supports "embedding" property to false.

2024-11-22 21:07 UTC, mdaconta commented on src/main/java/us/daconta/xlmeco/provider/impl/GrokProvider.java
> +        // Create the JSON body for the request
Is this from the OpenAI embedding?  I thought Grok did not support this...

2024-11-23 11:07 UTC, cdaconta commented
I made the changes you stated.

2024-11-23 14:15 UTC, mdaconta approved these changes

2024-11-23 14:15 UTC, merged

2024-11-23 14:16 UTC, mdaconta commented
merged!